[template.environment]
  GQL_HOST = "WordPress URL http://example.com"
  NUXT_IMAGE_DOMAINS = "e4c35c3c24.nxcli.io"

[build]
  command = "nuxt generate"

[images]
  remote_images = ["https://secure.woonuxt.com/.*"]
  remote_patterns = [
    { protocol = "https", hostname = "e4c35c3c24.nxcli.io" }
  ]
